# =============================================================
# routes/v6_routes.py
# Phase 6 — Deployment APIs
#
# FIXES APPLIED:
#   ✅ FIX 1:  Removed "id" from Swagger request payload
#   ✅ FIX 2:  UUID auto-generated by backend
#   ✅ FIX 3:  Legacy routes removed
#   ✅ FIX 4:  Bearer token auth enabled
#   ✅ FIX 5:  Swagger request/response examples fixed
#   ✅ FIX 6:  Early warning filters High + Critical
#   ✅ FIX 7:  Swagger lock icon + CURL auth support
#   ✅ FIX 8:  Hugging Face deployment compatible
#   ✅ FIX 9:  Proper FastAPI Query validation
#   ✅ FIX 10: Clean API documentation
#   ✅ FIX 11: Removed example documentation sections from docstrings
#              (EXAMPLE REQUEST BODY and SUCCESS RESPONSE blocks removed)
# =============================================================

from fastapi import (
    APIRouter,
    Depends,
    Query,
)

from models.k12_agent_models import (
    BatchInferencePayload,
)

from middleware.auth import (
    require_api_key,
)

from services.batch_inference_service import (
    run_batch_inference,
)

from services.early_warning_service import (
    get_early_warning_report,
)

# =============================================================
# ROUTER CONFIGURATION
# =============================================================

router = APIRouter(
    prefix="/api/v6",
    tags=["Phase 6 — Deployment"],
)

# =============================================================
# POST /api/v6/batch-inference
# =============================================================

@router.post(
    "/batch-inference",

    summary="Trigger Batch Inference",

    response_description=(
        "Run ML prediction for all students"
    ),

    dependencies=[
        Depends(require_api_key)
    ],
)
def trigger_batch_inference(
    payload: BatchInferencePayload,
):
    """
    Run batch ML prediction for all students.

    FEATURES:
    - Reads XLSX student data
    - Runs Nursery / Primary / Secondary ML models
    - Stores prediction results in Supabase
    - Updates:
        - early_warning_reports
        - batch_predictions
    - UUID is auto-generated automatically
    - Requires Bearer Authentication

    ============================================================
    AUTHENTICATION
    ============================================================

    Header:
    Authorization: Bearer YOUR_API_SECRET_KEY
    """

    return run_batch_inference(
        payload.dict()
    )

# =============================================================
# GET /api/v6/early-warning
# =============================================================

@router.get(
    "/early-warning",

    summary="Get Early Warning Report",

    response_description=(
        "Fetch High/Critical risk students"
    ),

    dependencies=[
        Depends(require_api_key)
    ],
)
def early_warning_report(

    academic_year: str = Query(
        default="",
        example="2026",
    ),

    limit: int = Query(
        default=5000,
        ge=1,
        le=10000,
    ),
):
    """
    Fetch High and Critical risk students.

    IMPORTANT:
    Run POST /api/v6/batch-inference first.

    FEATURES:
    - Reads from early_warning_reports
    - Filters:
        - High
        - Critical
    - Optional academic_year filter
    - Advisory-only reporting
    - No automatic restrictions/actions

    ============================================================
    AUTHENTICATION
    ============================================================

    Header:
    Authorization: Bearer YOUR_API_SECRET_KEY

    ============================================================
    EXAMPLE CURL
    ============================================================

    ```bash
    curl -X GET \\
    'https://your-domain/api/v6/early-warning?academic_year=2026&limit=5000' \\
    -H 'Authorization: Bearer YOUR_API_SECRET_KEY'
    ```
    """

    return get_early_warning_report(
        academic_year=academic_year,
        limit=limit,
    )
