# =============================================================
# models/k12_agent_models.py
# Pydantic request models for all K12 API routes
#
# FIXES APPLIED:
#   ✅ FIX: gr_number, student_name, std_div made Optional
#           (they are batch-level filters, not required fields)
#   ✅ FIX: threshold_days default set to 30
#   ✅ FIX: BatchInferencePayload fields match run_batch_inference()
# =============================================================

from pydantic import BaseModel, Field
from typing import Optional, List


# =========================
# COMMON BASE
# =========================
class BaseAgent(BaseModel):
    agent_id: str = Field(..., example="784ca818-3be4-4868-bdbb-b6548be50f50")


# =========================
# UC-FEE-01 (Defaulter)
# =========================
class DefaulterInput(BaseAgent):
    student_id: Optional[str] = Field(None, example="97382")    # kept for legacy
    class_name: Optional[str] = None
    threshold_days: int = 7


# =========================
# UC-FEE-03 (Structure)
# =========================
class StructureInput(BaseAgent):
    target_revenue: float = Field(..., example=500000)


# =========================
# UC-FEE-04 (NACH)
# =========================
class NachInput(BaseAgent):
    file_data: List[dict] = Field(
        ...,
        example=[{"gr_number": "GR2026001", "status": "rejected"}]
    )


# =========================
# UC-FEE-06 (Fraud)
# =========================
class FraudInput(BaseAgent):
    gr_number: Optional[str] = Field(None, example="GR2026001")
    student_id: Optional[str] = Field(None, example="97382")    # kept for legacy
    amount: float = Field(..., example=5000)
    status: str = Field(..., example="success")


# =========================
# UC-FEE-07 (Forecast)
# =========================
class ForecastInput(BaseAgent):
    history: List[float] = Field(..., example=[10000, 12000, 9000, 15000])
    months: int = Field(3, example=6)


# =========================
# Phase 6 — Batch Inference
#
# FIX: Removed "id" field — UUID is auto-generated by backend (uuid.uuid4())
#      Do NOT pass "id" in request payload.
#
# FIX: gr_number, student_name, std_div are Optional —
#      they are used as single-student filters only.
#      When omitted, the full XLSX file is processed.
#
# FIX: threshold_days default is 30 (overdue days threshold).
# =========================
class BatchInferencePayload(BaseModel):

    agent_id: str = Field(
        ...,
        example="c40a3e05-0b64-4332-80c6-0fcbd3067766"
    )

    academic_year: str = Field(
        ...,
        example="2026"
    )

    data_path: Optional[str] = Field(
        None,
        example="data/Fees Defaulter Report - Overall.xlsx"
    )

    mode: Optional[str] = Field(
        "annual",
        example="annual"
    )

    persist: Optional[bool] = Field(
        True,
        example=True
    )

    threshold_days: int = Field(
        30,
        example=30
    )

    # Optional single-student filters
    # When provided, only that student is processed from the XLSX
    gr_number: Optional[str] = Field(
        None,
        example=""
    )

    student_name: Optional[str] = Field(
        None,
        example=""
    )

    std_div: Optional[str] = Field(
        None,
        example=""
    )
